### ISSUE TITLE
Question about reconfiguration

### ISSUE THREAD

**Issue by dgiantsidi** [microsoft/Nimble#7]
Hi there,

1) Does the reconfiguration protocol allow for adding new nodes to the currently operating membership of endorsers or is the reconfiguration restricted to only replace existing endorsers?
E.g., if 3 endorsers are operating, can we add another 2 endorsers to improve the fault tolerance degree (if yes, how the existing endorsers pass from finalized to initialize state)? Or Nimble requires to spawn 5 fresh endorsers, finalize the previous 3 and reconfigure the new 5 with the latest state?

2) Also, are these 5 endorsers first being initialized/activated and then being attested by the client or the TEEs/TCB is first supposed to be attested before reconfig? 

3) Is there a TLS connection established between the coordinator and the endorsers? Likewise between coordinator and the clients? Importantly, how does the endorsers convince the client about the freshness of their attestation report? Can't a man-in-the-middle attack sign attestations of older (crashed or finalized) endorsers?

4) Why the endorsers need to verify that the latest state derives from the ledger? 

thanks much,
Dimitra

**Comment by sga001** [comment]
Hi Dimitra,

1. Yes. You can add new nodes. It will look as follows. The coordinator creates 5 new endorsers (note that 3 of them can run in the same machines as the existing 3 endorsers). The coordinator then finalizes the existing 3 endorsers, which will produce a quorum signature of view change. The coordinator then initializes and activates the 5 new endorsers, completing the reconfiguration.

2. When new endorsers are started they call the bootstrap function first which produces the attestation report. The coordinator keeps these reports so it can show them to clients later. The coordinator can proceed with the rest of the reconfiguration.  When the client connects to Nimble it requests the current configuration which includes these attestations.

3. The endorsers run in servers controlled/operated by the coordinator. The coordinator can choose to use TLS or not, since they are all within its own datacenter network. There is no TLS endpoint inside the endorser. The TLS endpoint runs in the untrusted code outside of the endorser. A few thoughts about old reports.

 - Old attestation reports by themselves are not useful. You need to have the signatures from initialize().
 - Old endorsers lose their private keys when they call finalize(), so having access to an old endorser is not useful. They can't do anything.
 - Clients always submit a nonce when they read from Nimble, so unless you control a quorum of endorsers in the current configuration you cannot replay old data.
 - Replaying old attestation reports and public keys can be done to fool clients into accepting a new configuration. But then the system is dead because none of those endorsers can work anymore (they don't have keys so they can't sign anything). This only violates liveness.

4. Otherwise the coordinator could drop data during a reconfiguration. The verify_state check ensures that the new set of endorsers is picking up from where a quorum of old endorsers left off.

**Comment by dgiantsidi** [comment]
Hi Sebastian,

Thanks for your reply!

I am still not sure about (4). The ledger resides in the untrusted storage so it cannot be trusted (for state continuity). The only way I can think of to trust the ledger is to force the endorser who owns it to fetch it, verify it is not compromized and produce a signature over the last blocks.  As such, the new endorsers will have the guarantee that the history they replay is genuine. I am not sure this is currently what Nimble is doing, maybe I got it work.

In addition to that, the signatures provided by the old set of endorsers during a reconfiguration contain the tail of the ledger, the prev and the current config. Now, since the reconfigured endorsers require a quorum of signatures that do agree on the latest state (tail) and at the same time the quorum will always contain at least one most-up-to-date replica, I am not sure *why* we need to replay the previous states of the ledger. Can't the new endorsers configure their state from the highest indexed block the receive as part of the set of signatures?

**Comment by sga001** [comment]
We go over this in the paper:

> 
> The coordinator must provide evidence that it is safe for the endorser to “take over” the initialized identity. 
> An endorser performs a sequence of checks: 
> 
> (1) it checks that a quorum of existing endorsers in E have been finalized; 
> (2) it checks that a quorum of new endorsers in N have been initialized with the same state; and
> (3) the state of a quorum of new endorsers is derived from the state of a quorum of existing endorsers by picking ledger tails
> with the highest positions seen in the quorum.
> 
> To prove (1) and (2), the coordinator provides Rexist and Rnext respectively. 
> To prove (3), the coordinator provides additional blocks (A) that can be appended to the tail of each of the
> ledgers that were supplied by existing endorsers when they called finalize (Mi) such that the resulting state equals M.


The part that I think you might be missing is that when the endorsers call finalize, they sign their current state (M). But each endorser might have a different state M. For example, endorsers E1 and E2 might be ahead than endorser E3 on ledger L1, while endorser E3 might be ahead of E1 and E2 on ledger L2 (because M is a key-value map of many ledgers).

So there is no one endorser that has "the latest" state, because "latest" is defined on a per-ledger basis because Nimble operates on all ledgers asynchronously.

So what the coordinator does is it picks the latest state m to initialize endorsers with during initialize. The coordinator can pick m however it likes. An honest coordinator will set m to be the tail of each ledger among all old endorsers.

Then, the coordinator will convince all new endorsers that there is a way to make all of them have the same state by showing how for each of the old endorsers, there is a series of appends that can be issued to their ledgers such that they will end up in the tail specified in "m".

**Comment by dgiantsidi** [comment]
Hello,

Yes, it makes sense :) I understand it now! Thanks for all the explanations and your time :)
